---
title: "MSiA 400 Lab1"
author: "Harish Chockalingam"
date: "10/28/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Problem 1a
data<-read.table('markov100.txt')
dm<-as.matrix(data)
state1<-c(1,rep(0,99))
state5<-state1%*%dm%*%dm%*%dm%*%dm%*%dm%*%dm%*%dm%*%dm%*%dm%*%dm
state5[5]

##The probablity after 10 steps to be in state 5 is 0.045091 
```

```{r}
#Problem 1b
data<-read.table('markov100.txt')
dm1<-as.matrix(data)
initial_state=c(1/3,1/3,1/3,integer(97))
state10<-initial_state%*%dm1%*%dm1%*%dm1%*%dm1%*%dm1%*%dm1%*%dm1%*%dm1%*%dm1%*%dm1
state10[10]

##The probablity after 10 steps to be in state 10 is 0.08268901 
```

```{r}
#Problem 1c
#Ax=b: 
data<-read.table('markov100.txt')
dm2<-as.matrix(data)
A<-t(dm2)-diag(100)
A[100,]<-c(rep(1,100))
b<-c(rep(0,99),1)
x<-solve(A)%*%b
x[1]

#steady state probablity of state 1 is 0.01256589
```

```{r}
#Problem 1d
data<-read.table('markov100.txt')
dm3<-as.matrix(data)
B<-dm3[1:99,1:99]
Q<-diag(99)-B
e<-c(rep(1,99))
m<-solve(Q)%*%e
m[1]

#The mean first passage time to state 100 from state 1, m_1_100, is 254.9395
```

```{r}
#Problem 2a
web_data<-read.table('webtraffic.txt')
web_data<-web_data[-1,]
web_data<-apply(as.matrix(web_data),2,as.numeric)
Traffic<-matrix(,nrow=9,ncol=9)
trans_vector<-colSums(web_data)
seq<-c(1,2,3,4,5,6,7,8,9)
for (i in seq){
  for (j in seq){
    Traffic[i,j]<-trans_vector[j+9*(i-1)]
  }
}

Traffic
#Traffic Matrix shown above
```

```{r}
#Problem 2b
web_data<-read.table('webtraffic.txt')
web_data<-web_data[-1,]
web_data<-apply(as.matrix(web_data),2,as.numeric)
Traffic<-matrix(,nrow=9,ncol=9)
trans_vector<-colSums(web_data)
seq<-c(1,2,3,4,5,6,7,8,9)
for (i in seq){
  for (j in seq){
    Traffic[i,j]<-trans_vector[j+9*(i-1)]
  }
}

Traffic[9,1]<-1000
TSM<-Traffic/rowSums(Traffic)
TSM
#One Step Transition Matrix shown above
```
```{r}
#Problem 2c
Q1<-t(TSM)-diag(9)
Q1[9,]<-c(rep(1,9))
b1<-c(rep(0,8),1)
Pi<-solve(Q1)%*%b1
Pi

#The steady state probablity vector Pi is shown above:
```

```{r}
#Problem 2d
B1<-TSM[1:8,1:8]
Q2<-diag(8)-B1
e1<-c(0.1,2,3,5,5,3,3,2)
m1<-solve(Q2)%*%e1
m1[1]

#The average time a visitor spends is 14.563 minutes
```
```{r}
#Problem 2e
temp1=0.3*Traffic[2,3]
temp2=0.2*Traffic[2,4]
Traffic2=Traffic
Traffic2[2,3]=Traffic[2,3]-temp1
Traffic2[2,4]=Traffic[2,4]-temp2
Traffic2[2,6]=Traffic[2,6]+temp1
Traffic2[2,7]=Traffic[2,7]+temp2
TSM2<-Traffic2/rowSums(Traffic2)

Q3<-t(TSM2)-diag(9)
Q3[9,]<-c(rep(1,9))
b2<-c(rep(0,8),1)
Pi2<-solve(Q3)%*%b2

comp<-var.test(Pi,Pi2)
comp
var(Pi)
var(Pi2)
Pi2

#There is not much variance between Pi and Pi2, and as the p-value is high there not much #significance. Pi has a slightly higher variance than Pi2. We can say that adding the new links #slightly improved the traffic
```

